"""Device-binding value computation (spec section 28).

A Local Key alone must never be a portable credential -- copying
``ash-pass-manager.key`` to another machine must not unlock the vault
there. This module computes a value that is stable on one device
across reboots but changes across a genuinely different device or a
fresh install, and is never itself treated as secret (it is mixed into
a KDF as extra context, not used as a key by itself, and does not need
to be kept confidential to preserve the vault's security -- see
``docs/SECURITY.md``).

Deliberately NOT used as a binding input, per spec section 28:
  * hostname alone  -- trivially user-changeable, and often reused
    across a person's own machines
  * username alone  -- often identical across machines (many people
    use "ash", "admin", etc. everywhere)
  * anything requiring root

Inputs actually used (``DEFAULT_BINDING_INPUTS``): each is individually
weak, but combined they distinguish "the same running Linux user
session" from "a different device or a fresh install" without
depending on any single fragile identifier. ``/etc/machine-id`` is
regenerated by a fresh OS install *specifically* so old bindings stop
matching there -- this is exactly why a disk swap or reinstall can
never brick the vault (see ``core.crypto.keyslots`` and the invariant
documented in ``docs/SECURITY.md``: it only ever invalidates the
device slot, and the master password always still works).

``compute_binding`` records which inputs were used to make each
particular value (``binding_inputs`` on the resulting key slot), so
re-deriving it always uses the exact same input set -- a transient
read failure (e.g. ``/etc/machine-id`` momentarily unreadable) can
never silently produce a *different* binding value that then gets
treated as "a new device"; it always either reproduces the same value
or the slot fails to unwrap and the caller falls back to the password.
"""

from __future__ import annotations

import getpass
import hashlib
import hmac
import os
from enum import Enum
from pathlib import Path

_MACHINE_ID_PATHS = (Path("/etc/machine-id"), Path("/var/lib/dbus/machine-id"))
_HMAC_CONTEXT = b"ash-pm-device-binding-v1"
_DOMAIN_PREFIX = b"ash-pm/binding/v1"
_ABSENT_MARKER = b"<absent>"


class BindingInput(str, Enum):
    MACHINE_ID = "machine_id"
    UID = "uid"
    USERNAME = "username"
    # Opt-in hardening only -- deliberately excluded from the default
    # set. A root filesystem UUID is brittle (resize, subvolume/overlay
    # layouts, and filesystem migration all change it) and adds little
    # once machine-id is already covered; see the module docstring.
    ROOT_FILESYSTEM_UUID = "root_filesystem_uuid"


DEFAULT_BINDING_INPUTS: tuple[BindingInput, ...] = (
    BindingInput.MACHINE_ID,
    BindingInput.UID,
    BindingInput.USERNAME,
)


def _read_machine_id() -> str | None:
    for path in _MACHINE_ID_PATHS:
        try:
            value = path.read_text(encoding="ascii").strip()
        except (OSError, UnicodeDecodeError):
            continue
        if value:
            return value
    return None


def _read_root_filesystem_uuid() -> str | None:
    # Deliberately unimplemented rather than guessed at: doing this
    # correctly needs a real UUID lookup (blkid-equivalent) which this
    # project already has via integration.usb.udisks2 for *removable*
    # media, but not for the root filesystem. Left as a documented,
    # explicit extension point -- opting into this input before it is
    # wired up simply means it is always treated as absent, which is
    # safe (see compute_binding's absent-marker handling) rather than
    # silently wrong.
    return None


def _component(kind: BindingInput) -> bytes | None:
    if kind is BindingInput.MACHINE_ID:
        machine_id = _read_machine_id()
        if not machine_id:
            return None
        return hmac.new(machine_id.encode("utf-8"), _HMAC_CONTEXT, hashlib.sha256).digest()
    if kind is BindingInput.UID:
        return str(os.getuid()).encode("utf-8")
    if kind is BindingInput.USERNAME:
        try:
            return getpass.getuser().encode("utf-8")
        except Exception:  # noqa: BLE001 - environment with no resolvable user
            return None
    if kind is BindingInput.ROOT_FILESYSTEM_UUID:
        value = _read_root_filesystem_uuid()
        return value.encode("utf-8") if value else None
    return None


def compute_binding(inputs: tuple[BindingInput, ...] = DEFAULT_BINDING_INPUTS) -> bytes:
    """Deterministically combine the requested inputs, in order, into
    one 32-byte binding value. A component that cannot be read is
    represented by a fixed marker rather than silently skipped, so
    "absent" and "present but empty" can never collide."""
    hasher = hashlib.sha256()
    hasher.update(_DOMAIN_PREFIX)
    for kind in inputs:
        value = _component(kind)
        hasher.update(kind.value.encode("ascii"))
        hasher.update(b"=")
        hasher.update(value if value is not None else _ABSENT_MARKER)
        hasher.update(b";")
    return hasher.digest()
