#!/usr/bin/env python3
"""Create a throwaway demo vault with entirely fake accounts, for local
development and testing only.

Exercises exactly the KDBX feature set the app depends on (see spec
section: validate pykeepass compatibility first, against a generated
demo vault, never the user's real database):

  - KDBX4 database creation (``pykeepass.create_database``)
  - a generated Key File (no master password -- matches this project's
    chosen "Key File only" configuration, spec section 2)
  - AES-256 encryption, **Argon2id** KDF (pykeepass's own default is
    actually Argon2d; ``create_vault()`` upgrades it in place and this
    script's own validation, plus ``tests/test_vault_kdbx.py``, assert
    the reopened database reports ``kdf_algorithm == "argon2id"`` -- see
    core/vault/kdbx.py's ``_upgrade_kdf_to_argon2id`` for exactly how)
  - custom string attributes (``PM_ServiceName``, ``PM_AppIdentifiers``,
    ``PM_AuthStrategy``, protected ``otp``, protected ``PM_RecoveryCodes``)
  - reading everything back through ``passman.core.vault.kdbx``, the same
    compatibility layer the real application uses -- this script IS the
    validation, not a separate mock.

Every credential below is fake, generated by this script, and used
nowhere else. Never point ``--out`` at a real vault location.
"""

from __future__ import annotations

import argparse
import json
import secrets
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from passman.core.auth.strategy import DEFAULT_STRATEGY, MULTI_PAGE_STRATEGY  # noqa: E402
from passman.core.security.memory import SecretBytes  # noqa: E402
from passman.core.totp.totp import TotpConfig, normalize_base32_secret  # noqa: E402
from passman.core.vault.kdbx import create_vault, open_vault  # noqa: E402
from passman.core.vault.models import RecoveryCode  # noqa: E402

FAKE_TOTP_SECRET = normalize_base32_secret("JBSWY3DPEHPK3PXP")  # RFC 4648 test vector, not a real secret


def _fake_recovery_codes(n: int = 8) -> list[RecoveryCode]:
    return [RecoveryCode(code=f"demo-{secrets.token_hex(4)}", used=False, label="") for _ in range(n)]


DEMO_ACCOUNTS = [
    dict(
        display_name="Demo Discord",
        service_name="Discord",
        username="demo.user#0001",
        password="Demo-Discord-Passw0rd!",
        url="https://discord.com/login",
        app_identifiers=["discord", "re:Discord"],
        strategy=DEFAULT_STRATEGY,
        totp=True,
        recovery_codes=False,
    ),
    dict(
        display_name="Demo GitHub",
        service_name="GitHub",
        username="demo-user",
        password="Demo-GitHub-Passw0rd!",
        url="https://github.com/login",
        app_identifiers=["github.com", "re:GitHub"],
        strategy=DEFAULT_STRATEGY,
        totp=True,
        recovery_codes=True,
    ),
    dict(
        display_name="Demo Google",
        service_name="Google",
        username="demo.user@example.invalid",
        password="Demo-Google-Passw0rd!",
        url="https://accounts.google.com",
        app_identifiers=["accounts.google.com", "re:Google"],
        strategy=MULTI_PAGE_STRATEGY,
        totp=True,
        recovery_codes=True,
    ),
    dict(
        display_name="Demo Steam",
        service_name="Steam",
        username="demo_steam_user",
        password="Demo-Steam-Passw0rd!",
        url="https://steamcommunity.com/login",
        app_identifiers=["steam", "re:Steam"],
        strategy=DEFAULT_STRATEGY,
        totp=False,
        recovery_codes=False,
    ),
]


def build_demo_vault(out_dir: Path, overwrite: bool = False) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    vault_path = out_dir / "Passwords.kdbx"
    keyfile_path = out_dir / "Key.key"
    (out_dir / "icons").mkdir(exist_ok=True)

    if vault_path.exists() or keyfile_path.exists():
        if not overwrite:
            raise FileExistsError(
                f"{vault_path} or {keyfile_path} already exists; pass --overwrite to replace."
            )
        vault_path.unlink(missing_ok=True)
        keyfile_path.unlink(missing_ok=True)

    handle = create_vault(vault_path, keyfile_path, password=None)
    for spec in DEMO_ACCOUNTS:
        uuid = handle.create_account(
            display_name=spec["display_name"],
            service_name=spec["service_name"],
            username=spec["username"],
            password=spec["password"],
            url=spec["url"],
            notes="Demo entry created by demo/create_demo_vault.py -- not a real credential.",
            app_identifiers=spec["app_identifiers"],
            auth_strategy_json=spec["strategy"].to_json(),
        )
        if spec["totp"]:
            handle.set_totp(uuid, TotpConfig(secret_base32=FAKE_TOTP_SECRET), issuer=spec["service_name"])
        if spec["recovery_codes"]:
            handle.set_recovery_codes(uuid, _fake_recovery_codes())
    handle.save()
    handle.close()
    return vault_path


def validate_roundtrip(vault_path: Path, keyfile_path: Path) -> None:
    """Re-open the just-created vault through the same code path the
    real application uses, and assert every feature came back correctly.
    Raises AssertionError with a specific message on any mismatch."""
    import pykeepass

    raw = pykeepass.PyKeePass(str(vault_path), keyfile=str(keyfile_path))
    assert raw.kdf_algorithm == "argon2id", f"expected argon2id, got {raw.kdf_algorithm}"
    assert raw.encryption_algorithm == "aes256", f"expected aes256, got {raw.encryption_algorithm}"
    assert raw.version == (4, 0), f"expected KDBX 4.0, got {raw.version}"
    print(f"[OK] KDBX version {raw.version}, KDF {raw.kdf_algorithm}, cipher {raw.encryption_algorithm}")

    handle = open_vault(vault_path, keyfile_path, password=None)
    summaries = handle.list_account_summaries()
    assert len(summaries) == len(DEMO_ACCOUNTS), f"expected {len(DEMO_ACCOUNTS)} entries, got {len(summaries)}"

    by_name = {s.display_name: s for s in summaries}
    for spec in DEMO_ACCOUNTS:
        summary = by_name.get(spec["display_name"])
        assert summary is not None, f"missing entry: {spec['display_name']}"
        assert summary.service_name == spec["service_name"], "service_name mismatch"
        assert summary.has_totp == spec["totp"], f"has_totp mismatch for {spec['display_name']}"
        assert summary.has_recovery_codes == spec["recovery_codes"], "has_recovery_codes mismatch"

        secrets_obj = handle.get_account_secrets(summary.entry_uuid)
        try:
            assert secrets_obj.username == spec["username"], "username mismatch"
            assert secrets_obj.password.to_str() == spec["password"], "password mismatch"
            assert secrets_obj.url == spec["url"], "url mismatch"
            assert tuple(spec["app_identifiers"]) == secrets_obj.app_identifiers, "app_identifiers mismatch"
            if spec["totp"]:
                assert secrets_obj.totp is not None, "totp missing after roundtrip"
                assert secrets_obj.totp.secret_base32 == FAKE_TOTP_SECRET, "totp secret mismatch"
            else:
                assert secrets_obj.totp is None, "unexpected totp present"
            if spec["recovery_codes"]:
                assert len(secrets_obj.recovery_codes) == 8, "recovery code count mismatch"
        finally:
            secrets_obj.wipe()
    handle.close()
    print(f"[OK] round-trip validated: {len(DEMO_ACCOUNTS)} demo accounts, all fields correct")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parent / "demo-vault")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args(argv)

    vault_path = build_demo_vault(args.out, overwrite=args.overwrite)
    print(f"[OK] demo vault created: {vault_path}")
    print(f"[OK] demo key file created: {args.out / 'Key.key'}")
    validate_roundtrip(vault_path, args.out / "Key.key")
    print("\nAll credentials in this vault are FAKE. Do not use for anything real.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
